### ISSUE TITLE
Playsound Exception. Speech Synthesis not working.

### ISSUE THREAD

**Issue by shlok10** [SupTechRM/Seven#7]
Error 263 for command:
        open ./output85.mp3
    The specified device is not open or is not recognized by MCI.

    Error 263 for command:
        close ./output85.mp3
    The specified device is not open or is not recognized by MCI.
Failed to close the file: ./output85.mp3
Traceback (most recent call last):
  File "C:\Users\Shilpa\Seven\core.py", line 46, in <module>
    SpeechSynthesizer("A new user I see. Welcome. Welcome to Seven. Let me introduce myself. I'm Seven. I'm a damn brilliant guy. That's all. Here let me get you through setup. Spell your name.", path="main/data/speech/empyrean-app-332014-6fdfdc87b1df.json")
  File "C:\Users\Shilpa\Seven\main\data\speech\RealtimeSpeech.py", line 52, in SpeechSynthesizer
    playsound.playsound(filename)
  File "C:\Users\Shilpa\AppData\Local\Programs\Python\Python310\lib\site-packages\playsound.py", line 72, in _playsoundWin
    winCommand(u'open {}'.format(sound))
  File "C:\Users\Shilpa\AppData\Local\Programs\Python\Python310\lib\site-packages\playsound.py", line 64, in winCommand
    raise PlaysoundException(exceptionMessage)
playsound.PlaysoundException:
    Error 263 for command:
        open ./output85.mp3
    The specified device is not open or is not recognized by MCI.

**Comment by anrawool** [comment]
Try downgrading you python interpreter version to 2.7 or 2.8. If not, do `pip uninstall playsound` then `pip install playsound==1.2.2`(These uninstall and install command must be done in the folder of the Seven project)
